eureka:
  instance:
    hostname: 123.233.240.221
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@123.233.240.221:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

spring:
  rabbitmq:
    host: 123.233.240.221
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"

monitor:
  hostname: 123.233.240.221
  port: 8040

auth-service:
    hostname: 123.233.240.221
    port: 5000
    contextPath: /uaa

auth-client-mgr:
  hostname: 123.233.240.221
  port: 8083
  contextPath: /ui

auth-client-server:
  hostname: 123.233.240.221
  port: 5003
  contextPath: /uas

config-center:
  user:
    name: user
    password: password
  hostname: 123.233.240.221
  port: 8888
  test: test1

gateway:
  hostname: 123.233.240.221
  port: 8060

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://${auth-service.hostname}:${auth-service.port}${auth-service.contextPath}/oauth/principal

