server:
  context-path: /uaa
  port: 5000

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}

management:
  security:
    enabled: false
  context-path: /mgmt

spring:
  datasource:
    url: jdbc:mysql://123.233.240.221:3306/sdgm
    username: root
    password: YFZXchy6629!@#123
#  datasource:
#    url: jdbc:h2:mem:user
#    driver-class-name: org.h2.Driver
#    schema: schema.sql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
