server:
  context-path: /uas
  port: 5003

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}

management:
  security:
    enabled: false
  context-path: /mgmt

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sdgm
    username: '{cipher}AQASpyTJJco1xIyy8MgHgZeFqzAsZASVEJ7S9a+zROBCPDyPaKE09nrFrrectf3rHU9WKNKir7nr5ut9n7EzYSH9nGnP77kRMeXpLco/WrqJvKHTyXRg85R3iuc5tw0J40xMFaUUEP5e5AxIwnimnHOYxexpOo0SOLtBoegS39n3T7+G1U7c5fSNBraraxJoujoSi1z/79cl0lYKg8428PEuZ8pProM7Nhy7UpFk/gF4kNLDElYXidyi5y3KvQh3cjG3BO3uRLDNLkJbJ5oUUmbS4WGrUsXYJDeN8loZE8BMhHiIcpgW8aiXslmWUR4GhQMihCnoAxfAjhgusgCH2U2qFv4vNO/PZwq5D4UXXAKE/aPhssBKmrlenHB+kNUljhc='
    password: '{cipher}AQBNAoDcjo8qdvadm2A5+RM0Dx07UW2hxu9DrG8SqHdzeM/P11EcZw3ygs0q/o3zyFvyfooKc9gp/HsMkcKW1MCcxtv7mCERld0RWfP+pep6ibyIhaUXQuYWGWHyFmc6jS9GLDkRXwdvCIzXztdIAqxafgZ6ikrLRjSKmAVI0d7AH3AGAhDkLEihoU/EMWKkJOfLUhsDRW+p2BfQ0JxMF1lL1xsmqLhWorsRzo7IIbDPi3lKNKuSloXy54uq3MqmW/B/zr3aoI35O0bqcn3JzqmkQAx6wGfRfW9dj12Kw+X2m9yBEmx6p3DqM+kk+9jUeLbw9p3PAJQg6qnSY27t1RB/S4yi0L+7xkQ8lZf88WMc8GJI6qjUgsHtqsyHKu0rsdtZlZJumkoUkItMrZI7sqVc'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update