server:
  port: 8084
  context-path: /rest
  session:
    cookie:
      name: UISESSION

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}

management:
  security:
    enabled: false
  context-path: /mgmt

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sdgm
    username: '{cipher}AQB28HymFp2NYxLo1RV55Ze/2tBlTELzn6ojakPUbkupLMeqqxg0yyxFtYHUo6WTKGoAxUATyrRoV+RRvayJyY87Y4NykQLvHNWsN/Tj77PfbWl6L1hn3KrOMDilD5zqibNYC4EOTOnyCSqhKg9JbzfWJ8Kq/SYomRKHUmIbKVKTMVe95s0gBMPJPiv8DdwzeZtwWKVDIRVEoSIDJdEJ+3avWS2RrTZgVIG56JH3bCQxZywJQAoTV7CK5Fz0KlfYUzXadWnug1iE7O8p+qbiu8nxfx1XyhwAY19Sby6ETdlBBKion4D0xy829Sp3byEJ7GG3yKEYaNapV7xRnJGyG8uecPGr70yCbUGiHhe73qEdhMiYoP6zXhBUJaahQ3jpmMI='
    password: '{cipher}AQB28HymFp2NYxLo1RV55Ze/2tBlTELzn6ojakPUbkupLMeqqxg0yyxFtYHUo6WTKGoAxUATyrRoV+RRvayJyY87Y4NykQLvHNWsN/Tj77PfbWl6L1hn3KrOMDilD5zqibNYC4EOTOnyCSqhKg9JbzfWJ8Kq/SYomRKHUmIbKVKTMVe95s0gBMPJPiv8DdwzeZtwWKVDIRVEoSIDJdEJ+3avWS2RrTZgVIG56JH3bCQxZywJQAoTV7CK5Fz0KlfYUzXadWnug1iE7O8p+qbiu8nxfx1XyhwAY19Sby6ETdlBBKion4D0xy829Sp3byEJ7GG3yKEYaNapV7xRnJGyG8uecPGr70yCbUGiHhe73qEdhMiYoP6zXhBUJaahQ3jpmMI='

security:
#  user:
#    name: tom
#    password: tom
  oauth2:
    client:
      clientId: svcb-service
      clientSecret: password
      accessTokenUri: http://${auth-client-server.hostname}:${auth-client-server.port}${auth-client-server.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://${auth-client-server.hostname}:${auth-client-server.port}${auth-client-server.contextPath}/current
