server:
  port: 8083
  context-path: /ui
  session:
    cookie:
      name: UISESSION

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}

management:
  security:
    enabled: false
  context-path: /mgmt

spring:
  datasource:
    url: jdbc:mysql://123.233.240.221:3306/sdgm
    username: root
    password: YFZXchy6629!@#123
security:
#设置自动授权
#  user:
#    name: tom
#    password: tom
  basic:
    enabled: false
  oauth2:
    client:
      clientId: ClientId
      clientSecret: secret
      accessTokenUri: http://${auth-service.hostname}:${auth-service.port}${auth-service.contextPath}/oauth/token
      userAuthorizationUri: http://${auth-service.hostname}:${auth-service.port}${auth-service.contextPath}/oauth/authorize
    resource:
      userInfoUri: http://${auth-service.hostname}:${auth-service.port}${auth-service.contextPath}/oauth/principal