server:
  port: 8084
  context-path: /rest
  session:
    cookie:
      name: UISESSION

eureka:
  instance:
    health-check-url-path: ${server.context-path}${management.context-path}/health
    status-page-url-path: ${server.context-path}${management.context-path}/info
    metadata-map:
      management.context-path: ${server.context-path}${management.context-path}

management:
  security:
    enabled: false
  context-path: /mgmt

spring:
  datasource:
    url: jdbc:mysql://192.168.50.254:3306/sdgm
    username: sdgm
    password: '{cipher}AQBNAoDcjo8qdvadm2A5+RM0Dx07UW2hxu9DrG8SqHdzeM/P11EcZw3ygs0q/o3zyFvyfooKc9gp/HsMkcKW1MCcxtv7mCERld0RWfP+pep6ibyIhaUXQuYWGWHyFmc6jS9GLDkRXwdvCIzXztdIAqxafgZ6ikrLRjSKmAVI0d7AH3AGAhDkLEihoU/EMWKkJOfLUhsDRW+p2BfQ0JxMF1lL1xsmqLhWorsRzo7IIbDPi3lKNKuSloXy54uq3MqmW/B/zr3aoI35O0bqcn3JzqmkQAx6wGfRfW9dj12Kw+X2m9yBEmx6p3DqM+kk+9jUeLbw9p3PAJQg6qnSY27t1RB/S4yi0L+7xkQ8lZf88WMc8GJI6qjUgsHtqsyHKu0rsdtZlZJumkoUkItMrZI7sqVc'

security:
#  user:
#    name: tom
#    password: tom
  oauth2:
    client:
      clientId: svcb-service
      clientSecret: password
      accessTokenUri: http://${auth-client-server.hostname}:${auth-client-server.port}${auth-client-server.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://${auth-client-server.hostname}:${auth-client-server.port}${auth-client-server.contextPath}/current
