server:
  port: 9091

logging:
  config: classpath:logback-spring.xml
  level: debug

# CAS服务地址
cas:
  server:
    url: http://123.233.240.221:8081/cas
    # CAS服务登录地址
    login_url: ${cas.server.url}/login
    # CAS服务登出地址
    logout_url: ${cas.server.url}/logout?service=${app.url}

# 应用访问地址
app:
  url: http://192.168.31.177:9091
  # 应用登录地址
  login_url: /login
  # 应用登出地址
  logout_url: /logout

eureka:
  instance:
    health-check-url-path: ${management.context-path}/health
    status-page-url-path: ${management.context-path}/info
    metadata-map:
      management.context-path: ${management.context-path}

management:
  security:
    enabled: false
  context-path: /mgmt

spring:
  datasource:
    url: jdbc:mysql://123.233.240.221:3306/sdgm
    username: '{cipher}AQASpyTJJco1xIyy8MgHgZeFqzAsZASVEJ7S9a+zROBCPDyPaKE09nrFrrectf3rHU9WKNKir7nr5ut9n7EzYSH9nGnP77kRMeXpLco/WrqJvKHTyXRg85R3iuc5tw0J40xMFaUUEP5e5AxIwnimnHOYxexpOo0SOLtBoegS39n3T7+G1U7c5fSNBraraxJoujoSi1z/79cl0lYKg8428PEuZ8pProM7Nhy7UpFk/gF4kNLDElYXidyi5y3KvQh3cjG3BO3uRLDNLkJbJ5oUUmbS4WGrUsXYJDeN8loZE8BMhHiIcpgW8aiXslmWUR4GhQMihCnoAxfAjhgusgCH2U2qFv4vNO/PZwq5D4UXXAKE/aPhssBKmrlenHB+kNUljhc='
    password: '{cipher}AQBNAoDcjo8qdvadm2A5+RM0Dx07UW2hxu9DrG8SqHdzeM/P11EcZw3ygs0q/o3zyFvyfooKc9gp/HsMkcKW1MCcxtv7mCERld0RWfP+pep6ibyIhaUXQuYWGWHyFmc6jS9GLDkRXwdvCIzXztdIAqxafgZ6ikrLRjSKmAVI0d7AH3AGAhDkLEihoU/EMWKkJOfLUhsDRW+p2BfQ0JxMF1lL1xsmqLhWorsRzo7IIbDPi3lKNKuSloXy54uq3MqmW/B/zr3aoI35O0bqcn3JzqmkQAx6wGfRfW9dj12Kw+X2m9yBEmx6p3DqM+kk+9jUeLbw9p3PAJQg6qnSY27t1RB/S4yi0L+7xkQ8lZf88WMc8GJI6qjUgsHtqsyHKu0rsdtZlZJumkoUkItMrZI7sqVc'
  redis:
      host: 123.233.240.221
      port: 6379

token:
  v: bearer 4830c2f5-4d08-44c2-8c04-68f7578ea4dd

security:
#  user:
#    name: tom
#    password: tom
  oauth2:
    client:
      clientId: svca-service
      clientSecret: password
      accessTokenUri: http://${auth-client-server.hostname}:${auth-client-server.port}${auth-client-server.contextPath}/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      user-info-uri: http://${auth-client-server.hostname}:${auth-client-server.port}${auth-client-server.contextPath}/current
